[package]
name = "some"
version = "0.1.0"
edition = "2018"
license = "MIT OR Apache-2.0"
description = "Use options slightly more easily. Or annoyingly"
readme = "README.md"
repository = "https://github.com/hybras/rust_some"

[dependencies]
